spring:
  application:
    name: games
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: postgresql
    open-in-view: true
  datasource:
    url: jdbc:postgresql://localhost:5432/games
    username: games
    password: games

server:
  port: 8080